name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Ensures full checkout
      - name: List files
        run: |
          pwd
          ls -la
          find . -name myConfigSL_Calc.js

      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      - name: Installing NPM packages
        run: npm install

      - name: Building project
        run: npm run build

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Downloading artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./build

      - name: List files
        run: |
          pwd
          ls -la
          find . -name myConfigSL_Calc.js
          
      - name: Deploying to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          publish_dir: ./build
    
      - name: Debug File Location
        run: |
          pwd
          ls -l
          find . -name myConfigSL_Calc.js

      - name: Install Dependencies
        run: |
          npm install axios  # Install axios specifically
    
      - name: Run Testim
        run: |
          npm i -g @testim/testim-cli
          testim -c "./myConfigSL_Calc.js" --suite "Calc"
